#Actividad 1
CREATE DATABASE PELUQUERIA_PERRITOS;

USE PELUQUERIA_PERRITOS;

#Actividad 2
CREATE TABLE DUENIO (
	DNI INT(10) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(50),
	primary key (DNI)
);

CREATE TABLE PERRO (
	ID_PERRO INT(10) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50),
    FECHA_NAC DATE,
    SEXO VARCHAR(20),
    DNI_DUENIO INT(10),
	primary key (ID_PERRO),
    foreign key (DNI_DUENIO) references DUENIO(DNI)
);

#Actividad 9
UPDATE DUENIO
SET DIRECCION = "LIBERTAD 123"
WHERE DNI = 35785528;
