#DB

################################################################################################################################################################

CREATE DATABASE PELUQUERIA_CANINA;

USE PELUQUERIA_CANINA;

CREATE TABLE DUENIO (
	DNI INT(10) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    TELEFONO VARCHAR(20),
    DIRECCION VARCHAR(50),
	PRIMARY KEY (DNI)
);

CREATE TABLE PERRO (
	ID_PERRO INT(10) NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(50),
    FECHA_NAC DATE,
    SEXO VARCHAR(20),
    DNI_DUENIO INT(10),
	PRIMARY KEY (ID_PERRO),
    FOREIGN KEY (DNI_DUENIO) REFERENCES DUENIO(DNI)
);

CREATE TABLE HISTORIAL (
	ID_HISTORIAL INT(10) NOT NULL AUTO_INCREMENT,
    FECHA VARCHAR(50),
    ID_PERRO INT(10),
    DESCRIPCION VARCHAR(100),
    MONTO FLOAT(10),
	PRIMARY KEY (ID_HISTORIAL),
    FOREIGN KEY (ID_PERRO) REFERENCES PERRO(ID_PERRO)
);

################################################################################################################################################################

INSERT INTO DUENIO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (35785528, "DANIELA", "SANCHEZ", "3518113800", "SOL DE MAYO 420");
INSERT INTO DUENIO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (35785527, "PEDRO", "ACUNIA", "3517123901", "COSTA 1626");
INSERT INTO DUENIO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (35785526, "JULIAN", "MARK", "3519134002", "MINERVA 368");
INSERT INTO DUENIO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (35785525, "PEDRO", "LORCA", "3516134103", "VALLE 1892");
INSERT INTO DUENIO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (35785524, "PEDRO", "GUEVARA", "3515124204", "MONTI 563");

INSERT INTO PERRO (ID_PERRO, NOMBRE, FECHA_NAC, SEXO, DNI_DUENIO) VALUES (1,"TYLER", "2008-09-08", "MACHO", 35785528);
INSERT INTO PERRO (ID_PERRO, NOMBRE, FECHA_NAC, SEXO, DNI_DUENIO) VALUES (2,"LOOKY", "2020-05-24", "FEMENINO", 35785527);
INSERT INTO PERRO (ID_PERRO, NOMBRE, FECHA_NAC, SEXO, DNI_DUENIO) VALUES (3,"FIRU", "2022-01-21", "MACHO", 35785526);
INSERT INTO PERRO (ID_PERRO, NOMBRE, FECHA_NAC, SEXO, DNI_DUENIO) VALUES (4,"LORI", "2016-11-07", "HEMBRA", 35785525);

INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (1, "2010-01-21", 1, "CORTE Y LAVADO", 150.00);
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (2, "2012-05-04", 1, "UNIAS Y LAVADO", 300.00);
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (3, "2013-06-23", 1, "CORTE Y LAVADO", 500.00);

INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (4, "2020-10-11", 2, "CORTE Y LAVADO", 700.00);
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (5, "2021-08-25", 2, "UNIAS Y LAVADO", 800.00);
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (6, "2021-10-05", 2, "CORTE Y LAVADO", 1200.00);

INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (7, "2022-03-05", 3, "CORTE Y LAVADO", 1200.00);
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (8, "2022-07-16", 3, "CORTE Y LAVADO", 1500.00);

INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (9, "2018-08-15", 4, "CORTE Y LAVADO", 500.00);
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (10, "2019-11-05", 4, "UNIAS", 600.00);
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (11, "2022-07-21", 4, "CORTE Y LAVADO", 1500.00);

################################################################################################################################################################
#EJERCICIO 1 Realice la consulta correspondiente para crear la tabla Perro, teniendo en cuenta sus claves foráneas y primarias.

CREATE TABLE PERRO (
    ID_PERRO INT(10) NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    FECHA_NAC DATE,
    SEXO VARCHAR(20),
    DNI_DUENIO INT(10),
    PRIMARY KEY (ID_PERRO),
    FOREIGN KEY (DNI_DUENIO) REFERENCES DUENIO(DNI)
);

################################################################################################################################################################
#EJERCICIO 2 Inserte en la tabla correspondiente un nuevo animal (perro) como paciente y el dueño asociado a ese animal.

#INSERTA DUEÑO
INSERT INTO DUENIO (DNI, NOMBRE, APELLIDO, TELEFONO, DIRECCION) VALUES (35785528, "DANIELA", "SANCHEZ", "3518113800", "SOL DE MAYO 420");

#INSERTA PERRO
INSERT INTO PERRO (ID_PERRO, NOMBRE, FECHA_NAC, SEXO, DNI_DUENIO) VALUES (1,"TYLER", "2008-09-08", "MACHO", 35785528);

###############################################################################################################################################################
#EJERCICIO 7 Obtener los ingresos percibidos en Julio del 2022

SELECT SUM(H.MONTO)
FROM HISTORIAL H
WHERE H.FECHA BETWEEN '2022-07-01' AND '2022-07-31';

################################################################################################################################################################
#EJERCICIO 8 Insertar un nuevo registro en la tabla historial de un perro cuyo ID Perro es igual a 10.

#INSERTA NUEVO PERRO CON ID 10
INSERT INTO PERRO (ID_PERRO, NOMBRE, FECHA_NAC, SEXO, DNI_DUENIO) VALUES (10, "MANI", "2021-10-12", "MACHO", 35785524);

#INSERTA REGISTRO DE HISTORIAL
INSERT INTO HISTORIAL (ID_HISTORIAL, FECHA, ID_PERRO, DESCRIPCION, MONTO) VALUES (12, "2022-07-03", 10, "CORTE Y LAVADO", 1500.00);

################################################################################################################################################################